### ISSUE TITLE
Saved File name is equal to last $script read in from the array $scriptarray

### ISSUE THREAD

**Issue by ssleeper** [pariswells/public-code#1]
https://github.com/pariswells/public-code/blob/0c951bd39d6f3e352b48a836ddc6af14090c2d07/DownloadSingleIntunepowershellScript.ps1#L170

Line 170 that saves the file with -Name $script.fileName uses the filename of the last script that was written out to the host to give a list of the ID's.

Using the ID as a value to lookup in the array I tested the following entered right above the New-Item and I believe it works well enough.  

$scriptFileName = $($scriptarray | where {$_.id -eq $scriptid}).fileName

You would also need to change the $script.fileName to $scriptFileName to reflect the new variable that is holding the filename from the line above.

**Comment by pariswells** [comment]
Updated , thanks !
